small_batch:
  optimizer:
    _target_: optax.sgd
    learning_rate: 1.07e-1
  num_epoch: 40
  batch_size: 256
  dp: False
  run_name: "SGD - small batch (Table 5)"

large_batch:
  optimizer:
    _target_: optax.sgd
    learning_rate: 3.68e-1
  num_epoch: 7
  batch_size: 1024
  dp: False
  run_name: "SGD - large batch (Table 5)"

small_batch_dp:
  optimizer:
    _target_: optax.sgd
    learning_rate: 3.32e-1
  num_epoch: 40
  batch_size: 256
  dp: False
  run_name: "SGD - small batch with DP (Table 5)"

large_batch_dp:
  optimizer:
    _target_: optax.sgd
    learning_rate: 4.46
  num_epoch: 7
  batch_size: 1024
  dp: False
  run_name: "SGD - large batch with DP (Table 5)"